on:
  push:
    branches:
      - "main"

jobs:
  test-conversion:
    runs-on: ubuntu-latest
    name: Convert README to PDF
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Convert README
        uses: willfantom/md2pdf-action@main
        id: md2pdf
        with:
          markdownSrcPattern: "README.md"
      - name: Check Conversion
        run: '[[ "${{ steps.md2pdf.outputs.convertedFiles }}" == "README" ]] && echo "Converted" || exit 1'
